# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

phrases = [
  "Things dogs are actually saying when they bark",
  "Things grown-ups wish they could still do",
  "Things you should never put in your mouth",
  "Things not to do in a hospital",
  "Things not to do while driving",
  "Things not to tell your mother",
  "Things paramedics shouldn't say to a patient on the way to the hospital",
  "Things people do when no one is looking",
  "Things that are harder than they look",
  "Things that are your favorite foods",
  "Things that confirm your house is haunted",
  "Things that make you feel stupid",
  "Things that make you giggle",
  "Things that must be magic",
  "Things that shouldn't be made into video games",
  "Things that shouldn't be passed from one generation to the next",
  "Things that smell terrible",
  "Things that you can trip over",
  "Things that you love to watch on tv",
  "Things that you shouldn't do in public",
  "Things that you shouldn't swallow",
  "Things that you shouldn't throw off of a building",
  "Things that would be fun to do in an elevator",
  "Things wouldn't want to be allergic to",
  "Things you can never find",
  "Things you do to get a job",
  "Things you do to relieve stress",
  "Things you do to stay warm",
  "Things you don't want to find in your bed",
  "Things you might find in a library",
  "Things you name home brewed beer",
  "Things you return from your christmas gifts",
  "Things you shop for on black friday",
  "Things you should be thankful for",
  "Things you should do to get ready for winter",
  "Things you should give as birthday gifts",
  "Things you should never put in your mouth",
  "Things you shouldn't attempt to juggle",
  "Things you shouldn't celebrate on your birthday",
  "Things you shouldn't do babysitting",
  "Things you shouldn't do in public",
  "Things you shouldn't do on your birthday",
  "Things you shouldn't do with glue",
  "Things you shouldn't give trick-or-treaters",
  "Things you shouldn't play catch with",
  "Things you shouldn't say to your in-laws",
  "Things you shouldn't say when trying to make a good impression",
  "Things you shouldn't tie to the roof of your car",
  "Things you shouldn't wear to a wedding/ funeral",
  "Things you shouldn't carve into a pumpkin",
  "Things you use to remove snow from your car",
  "Things you wish for",
  "Things you wish were included in a divorce settlement",
  "Things you would ask a psychic",
  "Things you would buy if you were rich",
  "Things you would do if you were a giant",
  "Things you would rather forget",
  "Things you would rather put off till tomorrow",
  "Things you would wish for if you were stranded on an island",
  "Things you wouldn't do for a million dollars",
  "Things you wouldn't want made into a movie",
  "Things you wouldn't want to do in cemetery",
  "Things you'd rather forget",
  "Things you shouldn't swallow",
  "Things you shouldn't throw off a building",
  "Things your parents forgot to tell you",
  "Things you'll do when you retire",
  "Things that would get a doctor sued for malpractice",
  "Things you shouldn't do in front of a crowd",
  "Things that give you a headache",
  "Things you wouldn't want to clean",
  "Things women know more about than men",
  "Things you shouldn't give as a gift",
  "Things that make you go ahhhh",
  "Things you shouldn't do at the dinner table",
  "Things you would consider strange to include on a resume",
  "Things there should be an award for",
  "Things you shouldn't do when havig dinner with the Queen",
  "Things you shouldn't make fun of",
  "Things you shouldn't teach your pets to do",
  "Things you shouldn't photograph",
  "Things you shouldn't do in the office",
  "Things that make ballet more exciting",
  "Things men know more about then women",
  "Things you would say to a pig if it could talk",
  "Things you can do to get rid of unwanted guests",
  "Things you notice about yourself as you get older",
  "Things you shouldn't say to your husband",
  "Things you would line up to see",
  "Things you shouldn't pay any attention to",
  "Things a chicken thinks about when the farmer picks up the eggs",
  "Things that make a good punch line",
  "Things you wish grew on trees",
  "Things you shouldn't say to you dentist",
  "Things that confirm you are guilty",
  "Things that tire you out",
  "Things you wish you could borrow from a library",
  "Things you shouldn't do while writing a final exam",
  "Things you shouldn't teach your parrot to say",
  "Things that shouldn't go into a time capsule",
  "Things that happen once in a blue moon",
  "Things kids know more about than adults",
  "Things that cause trouble",
  "Things that make you relax",
  "Things you wouldn't want to be allergic to",
  "Things you shouldn't shout at the top of your lungs",
  "Things you need to survive",
  "Things you shouldn't do in a car",
  "Things you can't stop",
  "Things you shouldn't do on vacation",
  "Things you would wish for if you found a genie in a bottle",
  "Things that seem to take an eternity",
  "Things that confirm you are losing your memory",
  "Things you would like as your last words",
  "Things firemen do between fires",
  "Things you shouldn't put off until tomorrow",
  "Things fish think about as they swim in their aquarium",
  "Things you could use as an excuse on judgement day",
  "Things that would make golf more exciting",
  "Things you shouldn't do in the house",
  "Things that would make work more exciting",
  "Things you would like to say to the President",
  "Things you would like to ask a psychic",
  "Things you shouldn't encourage your children to do",
  "Things you wish you could do with your feet",
  "Things you never see on television",
  "Things you wish worked by remote control",
  "Things you shouldn't exaggerate",
  "Things a waiter shouldn't do",
  "Things you shouldn't collect",
  "Things that confirm you still haven't grown up",
  "Things that require an assistant",
  "Things you shouldn't attempt at your age",
  "Things that would make school more exciting",
  "Things you shouldn't send in the mail",
  "Things that usually make you feel better",
  "Things you would like to do on vacation",
  "Things you would have said to Eve had she tricked you into eating the apple",
  "Things that cause an accident",
  "Things you shouldn't say to get out of a speeding ticket",
  "Things you shouldn't hold while riding a bike",
  "Things you wish you could predict",
  "Things you shouldn't give away",
  "Things you shouldn't advertise on a billboard",
  "Things that require a lot of patience",
  "Things you shouldn't say to your boss",
  "Things you wish you could erase",
  "Things you say to a telemarketer",
  "Things you wouldn't want to find in your sandwich",
  "Things you shouldn't put in your mouth",
  "Things you shouldn't do at a funeral",
  "Things that exhaust you",
  "Things you shouldn't do at the theatre",
  "Things you shouldn't write on a Valentine's card",
  "Things you shouldn't say to your grandmother",
  "Things that make you jump",
  "Things you won't find in a dictionary",
  "Things you shouldn't say to a flight attendant",
  "Things you shouldn't put on the front lawn",
  "Things that drive you mad",
  "Things you shouldn't do in your backyard",
  "Things you wouldn't want to find in your Christmas stocking",
  "Things you wish people would stop talking about",
  "Things you just can't beat",
  "Things you shouldn't do at a party",
  "Things you've paid too much for",
  "Things you call your mate",
  "Things you shouldn't laugh at",
  "Things you should keep to yourself",
  "Things you wouldn't want your mother to talk about with your girlfriend/boyfriend",
  "Things you would like to do in a blackout",
  "Things that make you cry",
  "Things you would do if you had super-human powers",
  "Things that make you go ooooh",
  "Things that really need a referee",
  "Things you shouldn't put on the kitchen table",
  "Things you shouldnt do in a hospital",
  "Things you shouldn't say to a police officer",
  "Things you wouldn't do for all the money in the world",
  "Things that would be considered a bad habit",
  "Things you would rather be doing right now",
  "Things astronauts complain about in space",
  "Things you wouldn't want to know about your grandmother",
  "Things that make you gag",
  "Things about men that frustrate you",
  "Things you shouldn't say to your mother",
  "Things a chimp thinks about when he sees you at the zoo",
  "Things an ideal mate would do for you",
  "Things you shouldn't forget",
  "Things a doctor shouldn't do while performing surgery",
  "Things you shouldn't say to the First Lady",
  "Things you hate about the hospital",
  "Things that should have an expiration date",
  "Things you shouldn't do at the beach",
  "Things people like about you",
  "Things you shouldn't say to your doctor",
  "Things that confirm you are losing your mind",
  "Things that dont last very long",
  "Things you didn't realize until it was too late",
  "Things you keep hidden",
  "Things you would like to see in your horoscope",
  "Things you shouldn't lend",
  "Things that take courage",
  "Things you shouldn't say to your teacher",
  "Things you shouldn't do right after you eat",
  "Things you shouldn't do on your first day on the job",
  "Things you shouldn't do at the circus",
  "Things women talk about when they go to the restroom together",
  "Things that should come with a manual",
  "Things you shouldn't do on a first date",
  "Things that confirm you have been abducted by aliens",
  "Things you never see in the country",
  "Things you shouldn't try to hold on to",
  "Things that prove you're in a bad restaurant",
  "Things you shouldn't say to your father",
  "Things you want to do before you die",
  "Things you know nothing about",
  "Things you dream about",
  "Things that could result in a war",
  "Things you shouldn't say to your wife",
  "Things you would have a robot do",
  "Things cats think about humans",
  "Things you would do if you were a dictator",
  "Things you would like to change",
  "Things you shouldn't pick up",
  "Things that would make meetings more exciting",
  "Things you never remember",
  "Things you keep in your car",
  "Things you shouldn't doodle on",
  "Things that don't make sense",
  "Things you wish you could do in your sleep",
  "Things you would like to study",
  "Things that would get you sent to the Principal's office",
  "Things you hope you can still do when you are 85",
  "Things that are none of your business",
  "Things you will never see in your lifetime",
  "Things that could spoil your appetite",
  "Things you don't like about family gatherings",
  "Things that could use a good cleaning",
  "Things you shouldn't do on an airplane",
  "Things that make you uncomfortable",
  "Things that must be magic",
  "Things that are funny",
  "Things that would get you discharged from the army",
  "Things you would like to make someone do under hypnosis",
  "Things you shouldn't title a children's book",
  "Things that don't exist but you wish they did",
  "Things you shouldn't do with a computer",
  "Things you would like to do with a bald head",
  "Things that make you scream",
  "Things that would get you fired",
  "Things you would hate to do for a living",
  "Things you shouldn't leave open",
  "Things that very old people shouldn't do",
  "Things you shouldn't do if you want to make a good first impression",
  "Things big dogs think about when they see a Chihuahua",
  "Things that make you feel young",
  "Things you shouldn't play catch with",
  "Things you wish you didn't know",
  "Things you shouldn't use as an opening line",
  "Things that make people jealous",
  "Things you love to shop for",
  "Things you shouldn't try to do in the dark",
  "Things you would do if you were invisible",
  "Things you shouldn't do in a group of people",
  "Things you can't believe someone actually did",
  "Things that make you angry",
  "Things you shouldn't have to pay for",
  "Things you wish had been taught in school",
  "Things that make you nervous",
  "Things you wish were delivered",
  "Things you shouldn't do in a cemetery",
  "Things that are impossible to measure",
  "Things you shouldn't do at your wedding",
  "Things that are better late than never",
  "Things you never see in the city",
  "Things you would like to try",
  "Things you shouldn't do while golfing",
  "Things you shouldn't experiment with",
  "Things that are useless",
  "Things you shouldn't do on a bus",
  "Things you shouldn't say to break the silence in a conversation",
  "Things you would do with a million dollars",
  "Things you wish you could buy out of vending machines",
  "Things you shoudn't do at a job interview",
  "Things you shouldn't accept from strangers",
  "Things you shouldn't do quickly"]
phrases.each{|phrase| Card.create(phrase: phrase)}
